---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: copy-chart
spec:
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: destination
        type: git
  params:
    - name: pathToSourceChart
      description: Path to Helm chart to copy
      default: chart
    - name: pathToDestinationChart
      description: Path to Helm chart to copy
      default: chart
  steps:
    - name: ls-build-sources
      image: busybox
      command: [ "ls", "-ltr", "/workspace/source" ]
    - name: create-destination-directory
      image: busybox
      command: ["mkdir", "-p", "/workspace/destination/$(params.pathToDestinationChart)"]
    - name: copy-chart
      image: busybox
      command: ["cp", "-r", "/workspace/source/$(params.pathToSourceChart)/", "/workspace/destination/$(params.pathToDestinationChart)"]
    - name: copy-chart-verify
      image: busybox
      command: [ "ls", "-l", "/workspace/destination/$(params.pathToDestinationChart)" ]
    - name: git-status
      image: alpine/git
      workingDir: /workspace/destination/
      command: [ "git", "status" ]
