---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: find-mvn-version
spec:
  params:
    - name: pathToContext
      description: The build context used by Kaniko
      default: /workspace/source
  results:
    - name: projectVersion
      description: The project version
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: find-version
      image: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
      workingDir: $(params.pathToContext)
      script: |
        #!/usr/bin/env bash
        mvn help:evaluate -Dexpression=project.version -q -DforceStdout | tee $(results.projectVersion.path)
