apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  resources:
    - name: git-app-repo
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image
