apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  resources:
    - name: git-app-repository
      type: git
  tasks:
    - name: build
      taskRef:
        name: build-docker-image
      resources:
        inputs:
          - name: git-app-repository
            resource: git-app-repository
