apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  resources:
    - name: git-app-repository
      type: git
    - name: image-registry
      type: image
  tasks:
    - name: find-version
      taskRef:
        name: find-mvn-version
      resources:
        inputs:
          - name: source
            resource: git-app-repository
    - name: build
      params:
        - name: tag
          value: $(tasks.find-version.results.projectVersion)
      taskRef:
        name: build-docker-image
      resources:
        inputs:
          - name: source
            resource: git-app-repository
        outputs:
          - name: image-registry
            resource: image-registry

