---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sync-task
spec:
  stepTemplate:
    envFrom:
      - secretRef:
          name: argocd-env-secret  # used for authentication (username/password or auth token)
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: image-registry
        type: image
  steps:
    - name: argocd-app-sync
      image: argoproj/argocd:v2.2.1
      script: |
        argocd login infra-argocd-server.default.svc.cluster.local:80 --grpc-web --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
        argocd app sync my-app --grpc-web --server infra-argocd-server.default.svc.cluster.local:80 --insecure
        argocd app wait my-app --health --grpc-web --server infra-argocd-server.default.svc.cluster.local:80 --insecure
